berries/berries/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

berries/main_app/urls.py
from django.urls import path # type: ignore
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('berries/', views.berry_index, name='berry-index'),
    path('berries/<int:berry_id>/', views.berry_detail, name='berry-detail'),
    path('berries/create/', views.BerryCreate.as_view(), name='berry-create'),
    path('berries/<int:pk>/update/', views.BerryUpdate.as_view(), name='berry-update'),
    path('berries/<int:pk>/delete/', views.BerryDelete.as_view(), name='berry-delete'),
    path('berries/<int:berry_id>/add-picking/', views.add_picking, name='add-picking'),
    path('farms/create', views.FarmCreate.as_view(), name='farm-create'),
    path('farms/<int:pk>/', views.FarmDetail.as_view(), name='farm-detail'),
    path('farms/', views.FarmList.as_view(), name='farm-index'),
    path('farms/<int:pk>/update/', views.FarmUpdate.as_view(), name='farm-update'),
    path('farms/<int:pk>/delete/', views.FarmDelete.as_view(), name='farm-delete'),
    path('berries/<int:berry_id>/associate-farm/<int:farm_id>/', views.associate_farm, name='associate-farm'),
    path('berries/<int:berry_id>/remove-farm/<int:farm_id>/', views.remove_farm, name='remove-farm'),
    path('accounts/signup/', views.signup, name='signup'),
]

berries/main_app/models.py
from re import M
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from localflavor.us.models import USStateField


# Create your models here.

class Farm(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    city = models.CharField(max_length=50)
    state = USStateField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('farm-detail', kwargs={'pk': self.id})


class Berry(models.Model):
    BERRY_CHOICES = {
        'BLACKBERRY': 'Blackberry',
        'BLUEBERRY': 'Blueberry',
        'CURRANT': 'Currant',
        'ELDERFLOWER': 'Elderflower',
        'GOJI': 'Goji',
        'GOOSEBERRY': 'Gooseberry',
        'MULBERRY': 'Mulberry',
        'RASPBERRY': 'Raspberry',
        'STRAWBERRY': 'Strawberry',
    }
    name = models.CharField(
        max_length=20,
        choices=BERRY_CHOICES,
        default=BERRY_CHOICES['STRAWBERRY'])
    variety = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    season = models.CharField(max_length=100)
    farms = models.ManyToManyField(Farm)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_name_display()} ({self.id})'

    def get_absolute_url(self):
        return reverse('berry-detail', kwargs={'berry_id': self.id})


class Picking(models.Model):
    date = models.DateField('Date picked')
    haul = models.DecimalField(max_digits=4, decimal_places=2)
    berry = models.ForeignKey(Berry, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.haul}lbs on {self.date}'

    class Meta:
        ordering = ['-date']

berries/main_app/forms.py
from django import forms
from .models import Picking

class PickingForm(forms.ModelForm):
    class Meta:
        model = Picking
        fields = ['date', 'haul']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'pick a date',
                    'type': 'date'
                }
            )
        }

berries/main_app/views.py
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from .models import Berry, Farm
from .forms import PickingForm

# Create your views here.

# function-based views


class Home(LoginView):
    template_name = 'home.html'


def about(request):
    return render(request, 'about.html')

@login_required
def berry_index(request):
    berries = request.user.berry_set.all()
    return render(request, 'berries/index.html', {'berries': berries})

@login_required
def berry_detail(request, berry_id):
    berry = Berry.objects.get(id=berry_id)
    farms_not_associated = Farm.objects.exclude(id__in = berry.farms.all().values_list('id'))
    picking_form = PickingForm()
    return render(request, 'berries/detail.html', {
        'berry': berry,
        'picking_form': picking_form,
        'farms': farms_not_associated
    })


# class-based views
class BerryCreate(LoginRequiredMixin, CreateView):
    model = Berry
    fields = ['name', 'variety', 'description', 'season']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class BerryUpdate(LoginRequiredMixin, UpdateView):
    model = Berry
    fields = ['variety', 'description', 'season']


class BerryDelete(LoginRequiredMixin, DeleteView):
    model = Berry
    success_url = '/berries/'

@login_required
def add_picking(request, berry_id):
    form = PickingForm(request.POST)
    if form.is_valid():
        new_picking = form.save(commit=False)
        new_picking.berry_id = berry_id
        new_picking.save()
    return redirect('berry-detail', berry_id=berry_id)

def signup(request):
    error_msg = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('berry-index')
        else:
            error_msg = 'invalid signup - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_msg': error_msg}
    return render(request, 'signup.html', context)

class FarmCreate(LoginRequiredMixin, CreateView):
    model = Farm
    fields = '__all__'

class FarmList(LoginRequiredMixin, ListView):
    model = Farm

class FarmDetail(LoginRequiredMixin, DetailView):
    model = Farm

class FarmUpdate(LoginRequiredMixin, UpdateView):
    model = Farm
    fields = ['name', 'description', 'city', 'state']

class FarmDelete(LoginRequiredMixin, DeleteView):
    model = Farm
    success_url = '/farms/'

@login_required
def associate_farm(request, berry_id, farm_id):
    Berry.objects.get(id=berry_id).farms.add(farm_id)
    return redirect('berry-detail', berry_id=berry_id)

@login_required
def remove_farm(request, berry_id, farm_id):
    Berry.objects.get(id=berry_id).farms.remove(farm_id)
    return redirect('berry-detail', berry_id=berry_id)

berries/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>About the Berry Picker</h1>
<hr />
<div class="page-content">
    <p>I like long romantic walks down the U-Pick rows. My first Django project includes:</p>
    <ul>
        <li>CRUD on selected berry varieties</li>
        <li>CRUD on berry farms</li>
        <li>CR on berry-picking excursions</li>
        <li>Authentication and Authorization</li>
    </ul>
    <p>Extra features beyond the scope of the assignment:</p>
    <ul>
        <li>Adding in the Farm model with many-to-many relationships and full CRUD</li>
        <li>Dynamically choosing shades of green based on the properties of each Farm class instance - I wrote a custom template function</li>
        <li>Associating the BERRY_CHOICES within the Berry model, for auto-selecting a matching image </li>
    </ul>
    <br>
    <br>
    <p>Coded by <a href="https://github.com/radford-coding/django-crud-app-lab/tree/main/berries">Matt Radford</a></p>
</div>
{% endblock %}

berries/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'images/icons8-berries-96.png' %}" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <title>Berry Picker</title>
    {% block head %}

    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/"><img src="{% static 'images/icons8-berries-96.png' %}" alt="The Berry Picker Logo" /></a>
        <h1>Berry Picker</h1>
      </div>
      {% comment %} <nav>
        <ul>
          <li>
            <a href="{% url 'berry-index' %}">All Berries</a>
          </li>
          <li>
            <a href="{% url 'berry-create' %}">Add a Berry</a>
          </li>
          <li>
            <a href="{% url 'about' %}">About</a>
          </li>
        </ul>
      </nav> {% endcomment %}
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li><a href="{% url 'berry-index' %}">All Berries</a></li>
            <li><a href="{% url 'farm-index' %}">All Farms</a></li>
            <li><a href="{% url 'berry-create' %}">Add a Berry</a></li>
            <li><a href="{% url 'farm-create' %}">Add a Farm</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>
          {% else %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'home' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      {% block content %}

      {% endblock %}
    </main>
  </body>
</html>

berries/main_app/templates/berries/detail.html
{% extends 'base.html' %}
{% load static %}
{% load color_calc %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/berries/berry-detail.css' %}" />
{% endblock %}

{% block content %}
  <section class="berry-container">
    <div class="berry-img">
      <img src="{% static 'images/' %}{{ berry.name|lower }}.png" alt="A {{ berry.name|lower }}" />
    </div>
    <div class="berry-details">
      <h2 class="card-title">{{ berry.variety }} {{ berry.get_name_display }}</h2>
      <p>{{ berry.description }}</p>
      <div class="berry-actions">
        <a href="{% url 'berry-update' berry.id %}" class="btn warn">edit</a>
        <a href="{% url 'berry-delete' berry.id %}" class="btn danger">delete</a>
      </div>
    </div>
  </section>

  <div class="pickings-farm-container">
    <section class="pickings">
      <div class="subsection-title">
        <h2>Picking Excursions</h2>
        {% comment %} <img src="{% static 'images/cat-cone.svg' %}" alt="An ice cream cone cat" />
        <img src="{% static 'images/cat-onigiri.svg' %}" alt="A cat as onigiri" />
        <img src="{% static 'images/kitty-kabob.svg' %}" alt="A kabob of kittens" /> {% endcomment %}
      </div>

      <div class="new-picking">
        <h3>I went picking!</h3>
        <form action="{% url 'add-picking' berry.id %}" method="post" class="subsection-content" autocomplete="off">
          {% csrf_token %}
          {{ picking_form.as_p }}
          <button type="submit" class="btn submit">Add Picking</button>
        </form>
      </div>

      <h3>Past Picking Excursions</h3>
      {% if berry.picking_set.all.count %}
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Haul</th>
            </tr>
          </thead>
          <tbody>
            {% for picking in berry.picking_set.all %}
              <tr>
                <td>{{ picking.date }}</td>
                <td>{{ picking.haul }}lbs</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
        <div class="subsection-content">
          <p>⚠️ You haven't picked {{ berry.variety }} {{ berry.get_name_display }} yet!</p>
        </div>
      {% endif %}
    </section>

    <section class="farms">
      <div class="subsection-title">
        <h2>Farms</h2>
        {% comment %} <img src="{% static 'images/string.svg' %}" alt="A ball of string" />
        <img src="{% static 'images/mouse.svg' %}" alt="A mouse" />
        <img src="{% static 'images/fish.svg' %}" alt="A fishy toy" /> {% endcomment %}
      </div>
      <h3>Farms with {{ berry.variety }} {{ berry.get_name_display }} planted</h3>
      <div class="subsection-content">
        {% if berry.farms.count %}
          {% for farm in berry.farms.all %}
            <div class="farm-container">
              <div class="color-block" style="background-color: {{ farm|color }}"></div>
              <a href="{% url 'farm-detail' farm.id %}">
                <p>
                  {{ farm.name }} <br /> in {{ farm.city }}, {{ farm.state }}
                </p>
              </a>
              <form action="{% url 'remove-farm' berry.id farm.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Remove Farm</button>
              </form>
            </div>
          {% endfor %}
        {% else %}
          <p class="no-farms">{{ berry.variety }} {{ berry.get_name_display }} isn't available at any farms!</p>
        {% endif %}
      </div>

      <h3>Available Farms</h3>
      <div class="subsection-content">
        {% if farms.count %}
          {% for farm in farms %}
            <div class="farm-container">
              <div class="color-block" style="background-color: {{ farm|color }}"></div>
              <p>
                {{ farm.name }} <br /> in {{ farm.city }}, {{ farm.state }}
              </p>

              <form action="{% url 'associate-farm' berry.id farm.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn submit">Add Farm</button>
              </form>
            </div>
          {% endfor %}
        {% else %}
          <p class="all-farms">All listed farms have {{ berry.variety }} {{ berry.get_name_display }} available!</p>
        {% endif %}
      </div>
    </section>
  </div>
{% endblock %}

berries/main_app/templates/berries/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/berries/berry-index.css' %}" />
{% endblock %}

{% block content %}
  <section class="page-header">
    <h1>Berry List</h1>
  </section>

  <section class="card-container">
    {% for berry in berries %}
      <div class="card">
        <a href="{% url 'berry-detail' berry.id %}">
            <div class="card-content">
              <div class="card-img-container">
                <img src="{% static 'images/' %}{{ berry.name|lower }}.png" alt="A {{ berry.name|lower }}" />
              </div>
              <h2 class="card-title">{{ berry.variety }} {{ berry.get_name_display }}</h2>
              <p>
                <small>{{ berry.description }}</small>
              </p>
            </div>
        </a>
      </div>
    {% endfor %}
  </section>
{% endblock %}

berries/main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}

{% block content %}
  <section class="logo-container">
    <div class="berry-container">
      <img src="{% static 'images/icons8-berries-96.png' %}" alt="The Berry Picker Berries" />
    </div>Berry Picker Home Page
  </section>
  {% if not user.is_authenticated %}
    <section>
      <form action="{% url 'home' %}" method="post" class="login">
        <h1>Login</h1>
        {% csrf_token %} {{ form.as_p }}
        <input type="hidden" name="next" value="{{ next }}" />
        <button type="submit" class="btn submit">Login</button>
      </form>
    </section>
  {% endif %}
{% endblock %}

berries/main_app/templates/main_app/berry_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="page-header">
    <h1>Delete Berry?</h1>
    <img src="{% static 'images/icons8-berries-96.png' %}" alt="The Berry Picker Berries" />
  </div>

  <h2>Are you sure you want to delete {{ berry.variety}} {{ berry.name }}?</h2>

  <form action="" method="post" class="form">
    {% csrf_token %}
    <a href="{% url 'berry-detail' berry.id %}" class="btn secondary">Cancel</a>
    <button type="submit" class="btn danger">Yes - Delete!</button>
  </form>
{% endblock %}

berries/main_app/templates/main_app/berry_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %}

{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>edit {{ object.name }}</h1>
    {% else %}
      <h1>Add a Berry</h1>
    {% endif %}
    <img src="{% static 'images/icons8-berries-96.png' %}" alt="The Berry Picker Berries" />
  </div>

  <form action="" method="post" class="form-container">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>
{% endblock %}

berries/main_app/templates/main_app/farm_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="page-header">
    <h1>Delete Farm?</h1>
    <img src="{% static 'images/icons8-berries-96.png' %}" alt="The Berry Picker Berries" />
  </div>
  <h2>Are you sure you want to delete {{ object.name }}?</h2>

  <form action="" method="post" class="form">
    {% csrf_token %}
    <a href="{% url 'farm-detail' farm.id %}" class="btn secondary">Cancel</a>
    <button type="submit" class="btn danger">Yes - Delete!</button>
  </form>
{% endblock %}

berries/main_app/templates/main_app/farm_detail.html
{% extends 'base.html' %}
{% load static %}
{% load color_calc %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/farms/farm-detail.css' %}" />
{% endblock %}
{% block content %}
  <div class="card" style="border-color: {{ farm|color }}">
    <div class="card-bg" style="background-color: {{ farm|color }}"></div>
    <div class="card-content">
      <h2>{{ farm.name }} <br /> in {{ farm.city }}, {{ farm.state }}</h2>
      <p>{{ farm.description }}</p>
    </div>
  </div>
  <a href="{% url 'farm-update' farm.id %}" class="btn warn">Edit</a>
  <a href="{% url 'farm-delete' farm.id %}" class="btn danger">Delete</a>
{% endblock %}

berries/main_app/templates/main_app/farm_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %}
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{ object.name }}</h1>
    {% else %}
      <h1>Add a Farm</h1>
    {% endif %}
    <img src="{% static 'images/farm.png' %}" alt="Farm" />
  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>
{% endblock %}

berries/main_app/templates/main_app/farm_list.html
{% extends 'base.html' %}
{% load static %}
{% load color_calc %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/farms/farm-index.css' %}" />
{% endblock %}
{% block content %}
  <section class="page-header">
    <h1>All Berry Farms</h1>
    {% comment %} <img src="{% static 'images/string.svg' %}" alt="A ball of string" />
    <img src="{% static 'images/mouse.svg' %}" alt="A mouse" />
    <img src="{% static 'images/post.svg' %}" alt="A scratching post" />
    <img src="{% static 'images/fish.svg' %}" alt="A fishy toy" /> {% endcomment %}
  </section>

  <section class="card-container">
    {% for farm in farm_list %}
      <div class="card" style="border-color: green">
        <div class="card-bg" style="background-color: {{ farm|color }}"></div>
        <a href="{% url 'farm-detail' farm.id %}">
          <div class="card-content">
            <h2>{{ farm.name }} <br /> in {{ farm.city }}, {{ farm.state }}</h2>
          </div>
        </a>
      </div>
    {% endfor %}
  </section>
{% endblock %}

berries/main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %}
{% block content %}
  <div class="page-header">
    <h1>Sign Up</h1>
    <img src="{% static 'images/icons8-berries-96.png' %}" alt="The Berry Picker Berries" />
  </div>
  {% if error_msg %}
    <p class="red-text">{{ error_msg }}</p>
  {% endif %}
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>
{% endblock %}